### ISSUE TITLE
Studying git

### ISSUE THREAD

**Issue by maksimk99** [java-fat-unicorn-team/ListOfGoods#3]
I am reading about git
start at 10.30
I am going to read it 2 hours

**Comment by aleksieiev** [comment]
1. It's not required to share that you're learning something for now. Usually It should be included in any other task without mentioning about that
2. It's also doesn't required for now mention when it has been started, I mean 10.30. Only day is important.
3. Last but not least: exactly this task shouldn't be here because it does not affect the functionality of the project.
